[pytest]
DJANGO_SETTINGS_MODULE = config.settings_test_pg
testpaths = tests
norecursedirs = dev_tests_backup
python_files = test_*.py

markers =
    slow: long-running tests
    integration: tests that require external services (db/redis)
    celery: celery-related tests
addopts =
    -ra
    --cov=apps
    --cov=config
    --cov-report=term-missing
    --cov-report=html

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(name)s: %(message)s
